name: Deploy all proyectos to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'proyectos/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get repo name
        id: repo
        run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Build all subprojects
        run: |
          mkdir -p docs/proyectos
          proyectos_list=""
          for d in proyectos/* ; do
            if [ -f "$d/package.json" ]; then
              project_name=$(basename "$d")
              proyectos_list="$proyectos_list<li><a href='./proyectos/$project_name/'>$project_name</a></li>"
              echo "Building $project_name"
              cd "$d"
              REPO_NAME="$REPO_NAME" PROJECT_DIR="$project_name" npm ci
              REPO_NAME="$REPO_NAME" PROJECT_DIR="$project_name" npm run build
              cd ../..
              mkdir -p "docs/proyectos/$project_name"
              cp -r "$d/dist/." "docs/proyectos/$project_name/"
            fi
          done
          # Crear index.html dinámicamente
          cat <<EOF > docs/index.html
          <!DOCTYPE html>
          <html lang="es">
          <head>
            <meta charset="UTF-8" />
            <title>Proyectos desplegados</title>
          </head>
          <body>
            <h1>Proyectos desplegados</h1>
            <ul>
              $proyectos_list
            </ul>
          </body>
          </html>
          EOF

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages